// <auto-generated />
using System;
using CssVision.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CssVision.Web.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260908170750_MakeLeadStageOptional")]
    partial class MakeLeadStageOptional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CssVision.Web.Domain.Crm.CrmActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Arquivado")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ArquivadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ArquivadoPorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AtualizadoPorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CriadoPorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DataHoraConclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DataHoraPrevista")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<int?>("LembreteMinutosAntes")
                        .HasColumnType("integer");

                    b.Property<Guid?>("OpportunityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResponsavelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Resultado")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Arquivado");

                    b.HasIndex("DataHoraPrevista");

                    b.HasIndex("LeadId");

                    b.HasIndex("OpportunityId");

                    b.HasIndex("ResponsavelId");

                    b.HasIndex("Status");

                    b.HasIndex("Tipo");

                    b.ToTable("CrmActivities", (string)null);
                });

            modelBuilder.Entity("CssVision.Web.Domain.Crm.CrmAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AtualizadoPorId")
                        .HasColumnType("uuid");

                    b.Property<string>("CaminhoArmazenamento")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CriadoPorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EnviadoPorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<Guid?>("OpportunityId")
                        .HasColumnType("uuid");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoConteudo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("EnviadoPorId");

                    b.HasIndex("LeadId");

                    b.HasIndex("OpportunityId");

                    b.ToTable("CrmAttachments", (string)null);
                });

            modelBuilder.Entity("CssVision.Web.Domain.Crm.CrmAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("DetalhesJson")
                        .HasColumnType("text");

                    b.Property<Guid?>("EntidadeId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntidadeTipo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("OcorridoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OcorridoEm");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("EntidadeTipo", "EntidadeId");

                    b.ToTable("CrmAuditLogs", (string)null);
                });

            modelBuilder.Entity("CssVision.Web.Domain.Crm.CrmLead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Arquivado")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ArquivadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ArquivadoPorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AtualizadoPorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Campanha")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Cidade")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("ConsentimentoContato")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ConsentimentoDataEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConsentimentoOrigem")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CriadoPorId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("DocumentoNormalizado")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EmailNormalizado")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<Guid?>("EtapaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Gclid")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("IndicadoPorLeadId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetaClickId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MetaFormId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("MetaLeadId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NomeOuRazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<string>("Origem")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ProdutoInteresse")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset?>("ProximoContatoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Regional")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid?>("ResponsavelId")
                        .HasColumnType("uuid");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.Property<string>("TelefoneNormalizado")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TipoIndicacao")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("TipoPessoa")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UltimoContatoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UtmMedium")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("UtmSource")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("UtmTerm")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("WhatsApp")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Arquivado");

                    b.HasIndex("CriadoEm");

                    b.HasIndex("DocumentoNormalizado")
                        .IsUnique()
                        .HasFilter("\"DocumentoNormalizado\" IS NOT NULL AND \"Arquivado\" = false");

                    b.HasIndex("EmailNormalizado")
                        .IsUnique()
                        .HasFilter("\"EmailNormalizado\" IS NOT NULL AND \"Arquivado\" = false");

                    b.HasIndex("EtapaId");

                    b.HasIndex("IndicadoPorLeadId");

                    b.HasIndex("MetaLeadId")
                        .IsUnique()
                        .HasFilter("\"MetaLeadId\" IS NOT NULL");

                    b.HasIndex("Origem");

                    b.HasIndex("ProximoContatoEm");

                    b.HasIndex("Regional");

                    b.HasIndex("ResponsavelId");

                    b.HasIndex("TelefoneNormalizado");

                    b.HasIndex("UltimoContatoEm");

                    b.ToTable("CrmLeads", (string)null);
                });

            modelBuilder.Entity("CssVision.Web.Domain.Crm.CrmLeadAssignmentHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AlteradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AlteradoPorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Motivo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("ResponsavelAnteriorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResponsavelNovoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlteradoEm");

                    b.HasIndex("AlteradoPorId");

                    b.HasIndex("LeadId");

                    b.HasIndex("ResponsavelAnteriorId");

                    b.HasIndex("ResponsavelNovoId");

                    b.ToTable("CrmLeadAssignmentHistories", (string)null);
                });

            modelBuilder.Entity("CssVision.Web.Domain.Crm.CrmLeadStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AtualizadoPorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Cor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CriadoPorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Fechada")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Ativa");

                    b.HasIndex("Ordem");

                    b.ToTable("CrmLeadStages", (string)null);
                });

            modelBuilder.Entity("CssVision.Web.Domain.Crm.CrmLeadTag", b =>
                {
                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("LeadId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("CrmLeadTags", (string)null);
                });

            modelBuilder.Entity("CssVision.Web.Domain.Crm.CrmLossReason", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AtualizadoPorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CriadoPorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Descricao")
                        .IsUnique();

                    b.ToTable("CrmLossReasons", (string)null);
                });

            modelBuilder.Entity("CssVision.Web.Domain.Crm.CrmNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AtualizadoPorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CriadoPorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("LeadId");

                    b.ToTable("CrmNotes", (string)null);
                });

            modelBuilder.Entity("CssVision.Web.Domain.Crm.CrmOpportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Arquivado")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ArquivadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ArquivadoPorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AtivoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AtualizadoPorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Concorrente")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CriadoPorId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("DataAdesao")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("DataEfetivaFechamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataPrevistaFechamento")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("EtapaDesde")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EtapaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Mensalidade")
                        .HasColumnType("numeric(14,2)");

                    b.Property<decimal?>("MensalidadeComDesconto")
                        .HasColumnType("numeric(14,2)");

                    b.Property<bool>("Migracao")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MotivoPerdaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<decimal?>("PagamentoAdesao")
                        .HasColumnType("numeric(14,2)");

                    b.Property<decimal?>("Porcentagem")
                        .HasColumnType("numeric(5,2)");

                    b.Property<int?>("ProbabilidadeFechamento")
                        .HasColumnType("integer");

                    b.Property<string>("ProdutoOuServico")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("ResponsavelId")
                        .HasColumnType("uuid");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<bool>("TermoAdesaoAceito")
                        .HasColumnType("boolean");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("ValorEstimado")
                        .HasColumnType("numeric(14,2)");

                    b.Property<decimal?>("ValorFinal")
                        .HasColumnType("numeric(14,2)");

                    b.HasKey("Id");

                    b.HasIndex("Arquivado");

                    b.HasIndex("CriadoEm");

                    b.HasIndex("DataEfetivaFechamento");

                    b.HasIndex("DataPrevistaFechamento");

                    b.HasIndex("EtapaId");

                    b.HasIndex("LeadId");

                    b.HasIndex("MotivoPerdaId");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("CrmOpportunities", (string)null);
                });

            modelBuilder.Entity("CssVision.Web.Domain.Crm.CrmPipelineStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AtualizadoPorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Cor")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CriadoPorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.HasIndex("Ordem");

                    b.ToTable("CrmPipelineStages", (string)null);
                });

            modelBuilder.Entity("CssVision.Web.Domain.Crm.CrmSalesGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AtualizadoPorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CriadoPorId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("MesReferencia")
                        .HasColumnType("date");

                    b.Property<int?>("MetaQuantidadeVendas")
                        .HasColumnType("integer");

                    b.Property<decimal>("MetaValor")
                        .HasColumnType("numeric(14,2)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("VendedorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VendedorId", "MesReferencia")
                        .IsUnique();

                    b.ToTable("CrmSalesGoals", (string)null);
                });

            modelBuilder.Entity("CssVision.Web.Domain.Crm.CrmStageHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AlteradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EtapaAnteriorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EtapaNovaId")
                        .HasColumnType("uuid");

                    b.Property<string>("MotivoPerdaDescricao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlteradoEm");

                    b.HasIndex("EtapaAnteriorId");

                    b.HasIndex("EtapaNovaId");

                    b.HasIndex("OpportunityId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CrmStageHistories", (string)null);
                });

            modelBuilder.Entity("CssVision.Web.Domain.Crm.CrmTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AtualizadoPorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Cor")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CriadoPorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("CrmTags", (string)null);
                });

            modelBuilder.Entity("CssVision.Web.Domain.Crm.CrmVeiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AtualizadoPorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CriadoPorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DataChegada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("Fipe")
                        .HasColumnType("numeric(14,2)");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Placa")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Rastreador")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("VistoriadorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OpportunityId")
                        .IsUnique();

                    b.HasIndex("Placa");

                    b.HasIndex("VistoriadorId");

                    b.ToTable("CrmVeiculos", (string)null);
                });

            modelBuilder.Entity("CssVision.Web.Domain.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("CssVision.Web.Domain.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("GestorComercialId")
                        .HasColumnType("uuid");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("GestorComercialId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CssVision.Web.Domain.Crm.CrmActivity", b =>
                {
                    b.HasOne("CssVision.Web.Domain.Crm.CrmLead", "Lead")
                        .WithMany("Atividades")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CssVision.Web.Domain.Crm.CrmOpportunity", "Opportunity")
                        .WithMany("Atividades")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CssVision.Web.Domain.Identity.ApplicationUser", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lead");

                    b.Navigation("Opportunity");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("CssVision.Web.Domain.Crm.CrmAttachment", b =>
                {
                    b.HasOne("CssVision.Web.Domain.Identity.ApplicationUser", "EnviadoPor")
                        .WithMany()
                        .HasForeignKey("EnviadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CssVision.Web.Domain.Crm.CrmLead", "Lead")
                        .WithMany("Anexos")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CssVision.Web.Domain.Crm.CrmOpportunity", "Opportunity")
                        .WithMany()
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EnviadoPor");

                    b.Navigation("Lead");

                    b.Navigation("Opportunity");
                });

            modelBuilder.Entity("CssVision.Web.Domain.Crm.CrmAuditLog", b =>
                {
                    b.HasOne("CssVision.Web.Domain.Identity.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CssVision.Web.Domain.Crm.CrmLead", b =>
                {
                    b.HasOne("CssVision.Web.Domain.Crm.CrmLeadStage", "Etapa")
                        .WithMany("Leads")
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CssVision.Web.Domain.Crm.CrmLead", "IndicadoPorLead")
                        .WithMany()
                        .HasForeignKey("IndicadoPorLeadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CssVision.Web.Domain.Identity.ApplicationUser", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Etapa");

                    b.Navigation("IndicadoPorLead");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("CssVision.Web.Domain.Crm.CrmLeadAssignmentHistory", b =>
                {
                    b.HasOne("CssVision.Web.Domain.Identity.ApplicationUser", "AlteradoPor")
                        .WithMany()
                        .HasForeignKey("AlteradoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CssVision.Web.Domain.Crm.CrmLead", "Lead")
                        .WithMany("HistoricoAtribuicoes")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CssVision.Web.Domain.Identity.ApplicationUser", "ResponsavelAnterior")
                        .WithMany()
                        .HasForeignKey("ResponsavelAnteriorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CssVision.Web.Domain.Identity.ApplicationUser", "ResponsavelNovo")
                        .WithMany()
                        .HasForeignKey("ResponsavelNovoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AlteradoPor");

                    b.Navigation("Lead");

                    b.Navigation("ResponsavelAnterior");

                    b.Navigation("ResponsavelNovo");
                });

            modelBuilder.Entity("CssVision.Web.Domain.Crm.CrmLeadTag", b =>
                {
                    b.HasOne("CssVision.Web.Domain.Crm.CrmLead", "Lead")
                        .WithMany("LeadTags")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CssVision.Web.Domain.Crm.CrmTag", "Tag")
                        .WithMany("LeadTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("CssVision.Web.Domain.Crm.CrmNote", b =>
                {
                    b.HasOne("CssVision.Web.Domain.Identity.ApplicationUser", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CssVision.Web.Domain.Crm.CrmLead", "Lead")
                        .WithMany("Notas")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("CssVision.Web.Domain.Crm.CrmOpportunity", b =>
                {
                    b.HasOne("CssVision.Web.Domain.Crm.CrmPipelineStage", "Etapa")
                        .WithMany("Oportunidades")
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CssVision.Web.Domain.Crm.CrmLead", "Lead")
                        .WithMany("Oportunidades")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CssVision.Web.Domain.Crm.CrmLossReason", "MotivoPerda")
                        .WithMany("Oportunidades")
                        .HasForeignKey("MotivoPerdaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CssVision.Web.Domain.Identity.ApplicationUser", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Etapa");

                    b.Navigation("Lead");

                    b.Navigation("MotivoPerda");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("CssVision.Web.Domain.Crm.CrmSalesGoal", b =>
                {
                    b.HasOne("CssVision.Web.Domain.Identity.ApplicationUser", "Vendedor")
                        .WithMany()
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("CssVision.Web.Domain.Crm.CrmStageHistory", b =>
                {
                    b.HasOne("CssVision.Web.Domain.Crm.CrmPipelineStage", "EtapaAnterior")
                        .WithMany()
                        .HasForeignKey("EtapaAnteriorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CssVision.Web.Domain.Crm.CrmPipelineStage", "EtapaNova")
                        .WithMany()
                        .HasForeignKey("EtapaNovaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CssVision.Web.Domain.Crm.CrmOpportunity", "Opportunity")
                        .WithMany("HistoricoEtapas")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CssVision.Web.Domain.Identity.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EtapaAnterior");

                    b.Navigation("EtapaNova");

                    b.Navigation("Opportunity");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CssVision.Web.Domain.Crm.CrmVeiculo", b =>
                {
                    b.HasOne("CssVision.Web.Domain.Crm.CrmOpportunity", "Opportunity")
                        .WithOne("Veiculo")
                        .HasForeignKey("CssVision.Web.Domain.Crm.CrmVeiculo", "OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CssVision.Web.Domain.Identity.ApplicationUser", "Vistoriador")
                        .WithMany()
                        .HasForeignKey("VistoriadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Opportunity");

                    b.Navigation("Vistoriador");
                });

            modelBuilder.Entity("CssVision.Web.Domain.Identity.ApplicationUser", b =>
                {
                    b.HasOne("CssVision.Web.Domain.Identity.ApplicationUser", "GestorComercial")
                        .WithMany()
                        .HasForeignKey("GestorComercialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GestorComercial");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("CssVision.Web.Domain.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("CssVision.Web.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("CssVision.Web.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("CssVision.Web.Domain.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CssVision.Web.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("CssVision.Web.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CssVision.Web.Domain.Crm.CrmLead", b =>
                {
                    b.Navigation("Anexos");

                    b.Navigation("Atividades");

                    b.Navigation("HistoricoAtribuicoes");

                    b.Navigation("LeadTags");

                    b.Navigation("Notas");

                    b.Navigation("Oportunidades");
                });

            modelBuilder.Entity("CssVision.Web.Domain.Crm.CrmLeadStage", b =>
                {
                    b.Navigation("Leads");
                });

            modelBuilder.Entity("CssVision.Web.Domain.Crm.CrmLossReason", b =>
                {
                    b.Navigation("Oportunidades");
                });

            modelBuilder.Entity("CssVision.Web.Domain.Crm.CrmOpportunity", b =>
                {
                    b.Navigation("Atividades");

                    b.Navigation("HistoricoEtapas");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("CssVision.Web.Domain.Crm.CrmPipelineStage", b =>
                {
                    b.Navigation("Oportunidades");
                });

            modelBuilder.Entity("CssVision.Web.Domain.Crm.CrmTag", b =>
                {
                    b.Navigation("LeadTags");
                });
#pragma warning restore 612, 618
        }
    }
}
